### ISSUE TITLE
Assets are not created in current folder if output param is not provided

### ISSUE THREAD

**Issue by azakharow** [onderceylan/pwa-asset-generator#1]
Readme tells that "The assets will be saved to the folder where the command is executed if no output-folder provided". To check this point, I'm executing the example from Readme without output folder provided like that: 
`pwa-asset-generator https://cdn.freebiesupply.com/logos/large/2x/amazon-icon-logo-png-transparent.png -p "20%" -b "linear-gradient(to top, #fad0c4 0%, #ffd1ff 100%)"`

It gives me an error:
`cli TypeError: path must be a string or Buffer`

**Comment by onderceylan** [comment]
Hey @azakharow, I noticed the same issue myself. I’m going to fix it, thanks for raising!
