### ISSUE TITLE
Adding type "jpg"

### ISSUE THREAD

**Issue by Sideral-Inc** [onderceylan/pwa-asset-generator#116]
Would it be possible to add "jpg" as type as well.

It's not a big issue but I usually always use ".jpg" extension and not ".jpeg".

**Comment by onderceylan** [comment]
Hi @Sideral-Inc, thanks for the issue. Can you please elaborate on this? What would be the added value if the images have .jpg extension instead of .jpeg?

**Comment by Sideral-Inc** [comment]
Hi @onderceylan,

Actually, I have some external automated tools that are configured to find and manipulate file with extension ".jpg".

Actually, it is more a "nice to have" feature / suggestion and asked it because I think it shouldn't add too much effort to add it.

**Comment by onderceylan** [comment]
Thanks for more information about your use case. I'll have a look at it soon :)

**Comment by onderceylan** [comment]
Hold due to: https://github.com/semantic-release/git/issues/187

**Comment by onderceylan** [comment]
Published this feature with pwa-asset-generator@2.2.0!
