### ISSUE TITLE
No splash screens shown on Vuejs PWA iOS

### ISSUE THREAD

**Issue by alexeigs** [onderceylan/pwa-asset-generator#128]
**Describe the bug**
I followed the steps and added the tags including the image links to the index.html file. Still I don't see any splash screen at startup but a white screen like before.

**To Reproduce**
I'm using VueJS and Quasar; everything else within the manifest and index.html works as expected in all regards, so I don't think it is related to the frameworks.

Tested on an iOS 13.3 device.

Has anything changed lately or is there another reasonable explanation why it may not show up?

**Comment by onderceylan** [comment]
Hi @alexeigs, thanks for the feedback! Can you please tell which device and orientation you test on? 

And HTML meta can be really helpful too.

**Comment by alexeigs** [comment]
@onderceylan Sure, here are some details:

Testing on an iPhone 7, iOS 13.3 in Portrait mode.

Part of the index.html:

```
<head>

// ...

 <meta name="apple-mobile-web-app-capable" content="yes">

  <link rel="apple-touch-startup-image" href="statics/splash-screens/apple-splash-2048-2732.png" media="(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)">
  <link rel="apple-touch-startup-image" href="statics/splash-screens/apple-splash-2732-2048.png" media="(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)">
  <link rel="apple-touch-startup-image" href="statics/splash-screens/apple-splash-1668-2388.png" media="(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)">
  <link rel="apple-touch-startup-image" href="statics/splash-screens/apple-splash-2388-1668.png" media="(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)">
  <link rel="apple-touch-startup-image" href="statics/splash-screens/apple-splash-1668-2224.png" media="(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)">
  <link rel="apple-touch-startup-image" href="statics/splash-screens/apple-splash-2224-1668.png" media="(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)">
  <link rel="apple-touch-startup-image" href="statics/splash-screens/apple-splash-1536-2048.png" media="(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)">
  <link rel="apple-touch-startup-image" href="statics/splash-screens/apple-splash-2048-1536.png" media="(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)">
  <link rel="apple-touch-startup-image" href="statics/splash-screens/apple-splash-1242-2688.png" media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)">
  <link rel="apple-touch-startup-image" href="statics/splash-screens/apple-splash-2688-1242.png" media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)">
  <link rel="apple-touch-startup-image" href="statics/splash-screens/apple-splash-1125-2436.png" media="(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)">
  <link rel="apple-touch-startup-image" href="statics/splash-screens/apple-splash-2436-1125.png" media="(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)">
  <link rel="apple-touch-startup-image" href="statics/splash-screens/apple-splash-828-1792.png" media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)">
  <link rel="apple-touch-startup-image" href="statics/splash-screens/apple-splash-1792-828.png" media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)">
  <link rel="apple-touch-startup-image" href="statics/splash-screens/apple-splash-1242-2208.png" media="(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)">
  <link rel="apple-touch-startup-image" href="statics/splash-screens/apple-splash-2208-1242.png" media="(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)">
  <link rel="apple-touch-startup-image" href="statics/splash-screens/apple-splash-750-1334.png" media="(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)">
  <link rel="apple-touch-startup-image" href="statics/splash-screens/apple-splash-1334-750.png" media="(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)">
  <link rel="apple-touch-startup-image" href="statics/splash-screens/apple-splash-640-1136.png" media="(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)">
  <link rel="apple-touch-startup-image" href="statics/splash-screens/apple-splash-1136-640.png" media="(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)">

</head>
```

Anything else that could help investigating?

**Comment by onderceylan** [comment]
Hey @alexeigs,

I've just tested it on iOS 13.3 iPhone 7 simulator and it all looks fine, for both icon and splash screens.

**Icon**
![image](https://user-images.githubusercontent.com/2641384/72969371-9e2fb600-3dc5-11ea-9bad-ce81243904c5.png)

**Splash Screen**
![image](https://user-images.githubusercontent.com/2641384/72969510-e5b64200-3dc5-11ea-9d63-776e1fa8d8b2.png)

I suspect there might be an issue with the path of the images, possibly affected by a base href? I'd troubleshoot as follows;

* Check in your browser tab if https://your-domain.com/statics/splash-screens/apple-splash-1136-640.png loads as expected.
* Change all the href of the images to the absolute URLs like the one above. 
* Test it again on the device/simulator.

**Comment by alexeigs** [comment]
@onderceylan The urls works, the image is available there. Also other meta tags work inside the index.html.

Could it interfere with something else in the index file or may it be in any way related to the manifest file?

**Comment by onderceylan** [comment]
Hey @alexeigs! I honesty have no idea what’s going wrong there. Can you upload it to somewhere so I can give it a look?

**Comment by alexeigs** [comment]
@onderceylan Ok, somewhat false alarm: it works! But unfortunately it is not updating for apps that have already been added to the home screen. While I force-update the service worker and refresh the whole app successfully whenever I update it, the splash screen does not get updated. Any idea how that may be achieved to include a new splash screen for existing users?

**Comment by onderceylan** [comment]
Ah, I haven’t suspected that. It explains.

I have bumped into the same issue while demonstrating the dark mode splash
screens.

The problem is not related to the service worker api or web app manifest.
iOS only respects the splash screen and icon meta tags when it’s added to
home screen, only on exact add time. As far as I know, there’s no way to
change them on an already added app.

I will document this on readme. Thanks for contributing!
