### ISSUE TITLE
Provide specific image path for html output

### ISSUE THREAD

**Issue by pixeline** [onderceylan/pwa-asset-generator#148]
I'm working on a Sapper/Svelte PWA. 
The images are to sit in a "static/images/app-icons" folder.
Sapper uses a `template.html` static html file to generate the SPA index.html
If i do 
```bash
pwa-asset-generator mathr-icon.png ./static/images/app-icons -o false -m static/site.webmanifest -i src/template.html -f true
```
The image path is of the like: 

```html 
<link rel="apple-touch-icon" sizes="120x120" href="../static/images/app-icons/apple-icon-120.png">
``` 
Where it should be 
```html 
<link rel="apple-touch-icon" sizes="120x120" href="./images/app-icons/apple-icon-120.png">
``` 

**Describe the solution you'd like**
I would like an additional parameter, for example:  iff (for Images Folder Href) to set the path to use in the html generation.

**Comment by onderceylan** [comment]
Hi @pixeline, thanks for the issue. This makes sense, it can make the lib more flexible for the expected output. I will have a look at it soon.
