### ISSUE TITLE
Images are generated in low-res

### ISSUE THREAD

**Issue by YM-KA** [onderceylan/pwa-asset-generator#175]
**Describe the bug**
Images for PWA Push notifications seem to be low-res.
Maybe I am just missing a setting somewhere? 🤓

**To Reproduce**
1. Execute cli command 'npx pwa-asset-generator logo.svg -i ./index.html -m ./manifest.json'
2. Open 'manifest.json' and copy the  "icons" section to my manifest.
3. Open the index.html and copy icon link to my index.html.
4. Install my app on mobile and receive a push notification
5. The presented app icon is low resolution

**Expected behavior**
Expect the icon to be high-res.

**System (please complete the following information):**
 - OS: Windows 10 + Android 9
 - node version: 8.11.1
 - yarn version 1.6.0
 - cli version 2.1.2

Edit:
I noticed there is an option for transparency, sorry for not reading the documentation. 😣
I have updated the ticket. 

Kind regards
K

**Comment by onderceylan** [comment]
Hi @YM-KA, thanks for the feedback! 

For the transparency issue, you can follow the recipe in the README: https://github.com/onderceylan/pwa-asset-generator#how-can-i-generate-a-png-image-with-transparency

About low resolution, I need more info as this is something I haven't faced myself. Would it be possible to send your index.html, manifest.json and images as a package for inspection? It would be great if you can deploy a prototype to glitch or codesandbox. I also need to know where you test the push notifications at, on Windows desktop or Android, what's the target device?

**Comment by YM-KA** [comment]
Hi @onderceylan , thank you for the reply! 
I will follow the recipe in the README. 😀

The device I have tested push notifications on is Android 9. 
I have emailed you the address to a site where you can inspect the index.html and manifest.json.

Kind regards /K

**Comment by onderceylan** [comment]
I inspected the app in your email and it looks like a low-res favicon is used for the notification icons. I also went through the notification display implementation of the app, and it has the following options for the notification;

```
var options = {
    body: data.content,
    icon: '/images/icons/favicon-32x32.png', //96x96
    badge: '/images/icons/favicon-32x32.png', //96x96
    data: {
      url: data.openUrl
    }
  }
```

The `icon` there should be the one generated by the library, like: `/images/icons/manifest-icon-512.png` - that should fix your low-res issue!

____________

I also suggest you to remove 3 different favicon declaration in your index.html file. 

```
<link rel="shortcut icon" href="/images/icons/favicon.ico">
<link rel="icon" type="image/png" sizes="32x32" href="/images/icons/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/images/icons/favicon-16x16.png">
```

The warning below is for the first meta without `sizes` declaration.

<img width="717" alt="Screenshot 2020-03-02 at 18 31 45" src="https://user-images.githubusercontent.com/2641384/75701642-69f8c080-5cb4-11ea-9cd1-c32899fc6d28.png">

PWA asset generator can also generate a favicon for you if you wish, you can see the options and usage for details.

**Comment by onderceylan** [comment]
@YM-KA, thanks for using PWA asset generator and I hope my feedback will fix your issue. If not, feel free to open a new ticket!

**Comment by YM-KA** [comment]
Thank you so much for all your help! I had totally missed that! 😳
I will definitely use the option to generate correct favicons. 

Thanks for a awesome library!
