### ISSUE TITLE
Splash Screen not showing in landscape on iOS 12.4

### ISSUE THREAD

**Issue by ecjs** [onderceylan/pwa-asset-generator#18]
First of all: **awesome package.** Such a good idea!

In order for me to get splash screens to work on (2) separate iOS devices (iPhone XS Max + iPad mini) both running iOS 12.4, I had to add ` and (orientation: landscape)` as well as maintaining the `device-width` and `device-height` dimensions as its portrait counterpart.

For instance, this got landscape working on my iPhone XS Max:

```
<link
  rel="apple-touch-startup-image"
  href="/static/images/splash/apple-splash-1242-2688.png"
  media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
/>
<link
  rel="apple-touch-startup-image"
  href="/static/images/splash/apple-splash-2688-1242.png"
  media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)"
/>
```

This is what was generated by this package (only portrait works):
```
<link rel="apple-touch-startup-image" href="apple-splash-1242-2688.png" media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3)">
<link rel="apple-touch-startup-image" href="apple-splash-2688-1242.png" media="(device-width: 896px) and (device-height: 414px) and (-webkit-device-pixel-ratio: 3)">
```

You would think that the way landscape meta tags are currently generated would be fine... **Thanks Apple**

**Comment by onderceylan** [comment]
Hey @ecjs, thanks a lot for your feedback and detailed issue explanation! I totally missed out orientation in the query, I’m going to fix it and publish a release asap.

**Comment by ecjs** [comment]
No problem! While you are at it, you may want to add iPad Pro (12.9")!

```
<link
  rel="apple-touch-startup-image"
  href="/static/images/splash/apple-splash-2048-2732.png"
  media="(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
/>
<link
  rel="apple-touch-startup-image"
  href="/static/images/splash/apple-splash-2732-2048.png"
  media="(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)"
/>
```

**Comment by onderceylan** [comment]
Sure, I will look into it! Thanks
