### ISSUE TITLE
Question: Does this work with Angular 9?

### ISSUE THREAD

**Issue by alexkaufman06** [onderceylan/pwa-asset-generator#188]
Wondering how well this works with the latest version of Angular and if there are any recommended steps to follow?

**Comment by onderceylan** [comment]
Hi Alex, it works perfectly fine with Angular too. 

You can point out manifest.webmanifest and index.html files in your project folder for automatic updates of icon and splash screen declarations. Documentation should be a good guideline. Please share if you face any issues.
