### ISSUE TITLE
Option to have self-closing html tags

### ISSUE THREAD

**Issue by zanettin** [onderceylan/pwa-asset-generator#192]
**Is your feature request related to a problem? Please describe.**
it's a feature request. currently the output for html meta tags are non self-closing tags. which works fine for html files but not in the context of JSX.

**Describe the solution you'd like**
Provide an option to get self-closing html meta tags.
current:
```
<meta name="apple-mobile-web-app-capable" content="yes">
<link rel="icon" type="image/png" sizes="196x196" href="assets/favicon-196.png">
```

expected:
```
<meta name="apple-mobile-web-app-capable" content="yes" />
<link rel="icon" type="image/png" sizes="196x196" href="assets/favicon-196.png" />
```

**Describe alternatives you've considered**
i could parse it by my self 🤣 

**Additional context**
should be clear otherwise feel free to ask 👍 

thank you very much for this great tool! totally love it ❤️

**Comment by onderceylan** [comment]
Hi @zanettin, thank you for using PAG and opening this feature request. What type of project setup do you have? Many of the frameworks, including jsx based template adapters use a single index.html entry. Isn't it the case for you too?

**Comment by zanettin** [comment]
Thank you very much for your kind reply! I‘am using next.js with a custom _document.tsx file where all meta headers are defined. Since all the requests are handled on server side rendering, no physical index.html file is in the project itself but generated per request on the nodejs instance. the injection of the tags directly into a js/ts file fails but thats ok for me personally. just thought about the above mentioned option to make the copy/past even easier. thanks again for your work on this project and have a nice weekend.

**Comment by onderceylan** [comment]
Thanks for the additional info @zanettin! I will look into this and get back to you soon. It's my pleasure providing this lib to the community, enjoy :)
