### ISSUE TITLE
PNG Optimisation

### ISSUE THREAD

**Issue by smth** [onderceylan/pwa-asset-generator#194]
There seems to be potential to (further) optimise the produced PNGs. I just tried running a couple of icons through [ImageOptim](https://github.com/ImageOptim/ImageOptim) with lossless compression and reduced the size of the files by about 50%.

**Comment by onderceylan** [comment]
Hi @smth, thanks for using PAG and for opening this feature request. Indeed, there's a big potential of image optimization for both PNG and JPEG images.

I'd like to keep Puppeteer as main dependency for image generation on this library, so I'm tightly coupled on what Puppeteer provides for it's screenshot feature for now. 

There are a couple of possibilities to introduce the image optimization;

* Using JPEG type with compression as an output format if transparency is not needed for the Apple splash screens, I assume it's not even necessary for almost all cases. Would that be an alternative for your use case?

* Creating an issue on https://github.com/puppeteer/puppeteer requesting such format / compression.

* Using an app like https://squoosh.app/ via Puppeteer to compress each generated image. I still need to test the compressed image formats on iOS though to validate it's still compatible with their splash screen display flow. This sounds like a nice challenging path within the scope of this lib but it will also require a lot of effort. So, if anyone is willing to contribute, it's most welcome.

**Comment by onderceylan** [comment]
I've added docs to guide users over the compression possibilities and decided to leave this concern out of the scope of this library.

**Comment by StanzillaManticore** [comment]
I don't think that just switching to JPG solves this issue tbh.

**Comment by onderceylan** [comment]
Hey @StanzillaManticore, thanks for your feedback. I think the opposite, mainly due to library's main use case;

* The icon and splash screen images generated for PWAs are most of the times generated with a background, without transparency. So, using JPG type with a compression is already a big improvement.
* Only favicons with transparency must be generated with PNG output.

Can you please share your use case of PNGs? I might be missing something.

**Comment by StanzillaManticore** [comment]
Well mostly that, some files need to be PNG and those can always be optimized so using something like imagemin during compilation is still able to shave of a few bytes. But not sure if that is inside the scope of this project or should be left to web owners :)
