### ISSUE TITLE
Emulate dark mode in screen capture of html files

### ISSUE THREAD

**Issue by jasonhibbs** [onderceylan/pwa-asset-generator#227]
**Is your feature request related to a problem? Please describe.**
I’m generating screens from an index.html and was hoping to use `@media (prefers-color-scheme: dark)` to make dark mode easy.

**Describe the solution you'd like**
I’d like `--dark-mode` to emulate this media feature during the screen capture process.

**Describe alternatives you've considered**
~I guess I have to make my `<html>` element transparent and add use the `--background` flag instead.~
I’ll have to update the `<html>` background colour for each mode because `--background` only applies to image sources.

**Additional context**

I believe this is possible using something like: `emulateMediaFeatures([{name: 'prefers-color-scheme', value: 'dark' }])` found in [this repo](https://github.com/tomayac/dark-mode-screenshot/blob/master/dark-mode-screenshot.js).

**Comment by onderceylan** [comment]
@jasonhibbs thanks for using the lib and giving this feedback. It makes a lot of sense, I wonder how I missed that. Thanks! I will look into it soon.
