### ISSUE TITLE
Update documentation for clear input requirements

### ISSUE THREAD

**Issue by shnigi** [onderceylan/pwa-asset-generator#234]
**Describe the bug**
This generated splash screen overrides Android icon. When user adds the app to the home screen default Android icons are not used anymore but the new generated ios splashscreen takes over.

**To Reproduce**
1. Add Android icon which is different to IOS splash screen
2. Generate IOS splash screen with this tool
3. Install app for Android phone

**Expected behavior**
App Icon should be specified Android icon but it is splash screen instead.

**System (please complete the following information):**
Not related to the system

**Additional context**
Device width is deprecated, so I wonder how trusted it is to use?
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/device-width

**Comment by onderceylan** [comment]
Hey @shnigi, thanks for using the library and sharing your feedback! 

Can you please share a bit more context? Like attaching the files (manifest.json) and stating what you expect to see and what's unexpected? 

From where I look, iOS splash screens have no place in Android ecosystem and they're declared in two very different ways.

**Comment by shnigi** [comment]
@onderceylan Hi thanks for your comment. I had a second look and looks like I was missing the --splash-only parameter. The default values wrote to my manifest.json which then changed the icon so I believe this is user error from my side. 

However I still would like to have more information about the deprecated device width usage.

Second thing is that I don't know what kind of image I should apply for this tool. Could you please provide some kind of guidelines what size image I need to provide, what are the safe margins for logo / splash image? 

Thirdly, I tried this with Iphone 6s with ios 13.3 and the generated splash screen or icon didn't work for some reason. Any ideas?

**Comment by onderceylan** [comment]
@shnigi I'm going to add answers to your questions to the readme. 

> However I still would like to have more information about the deprecated device width usage.

Device width media query is still being used by iOS to match splash screen images. When it's an exact match with device's resolution, it display the splash screen as a launch image on bookmarks/PWAs added to home screen.

> Second thing is that I don't know what kind of image I should apply for this tool. Could you please provide some kind of guidelines in the readme what size image I need to provide, what are the safe margins for logo / splash image etc?

Your input image is being scaled to fix the viewport of the target device while generating splash screens. There's no particular safe margin requirement as margins are added by default. That being said, you can customize the margins as it's described on the readme.

> Thirdly, I tried this with Iphone 6s with ios 13.3 and the generated splash screen or icon didn't work for some reason. Any ideas?

Can you please share a code snippet or a URL where I can have more context about your issue?
