### ISSUE TITLE
Doesn't write to index.html when using -c option

### ISSUE THREAD

**Issue by guidupuy** [onderceylan/pwa-asset-generator#26]
Should be pretty self explanatory... unless I'm missing something?

Great stuff by the way. Incredibly helpful.

**Comment by onderceylan** [comment]
Hey @guidupuy, thanks a lot for your feedback! I think you expect apple icon tags to appear on index.html file, right?

**Comment by guidupuy** [comment]
Right!

**Comment by onderceylan** [comment]
Ok, it's clear as a bug. I will fix it asap. Thanks for raising the issue!
