### ISSUE TITLE
-h used for both --path-override and --splash-only 

### ISSUE THREAD

**Issue by dalmo3** [onderceylan/pwa-asset-generator#263]
Here I was writing a really long, fully reproducible bug description on how icons were not being generated until I realised I was using `-h` for overriding path, but it **also** prevents generating icons.
 
Of course the workaround is using full flag names, but still needs fixing imo.

**Comment by onderceylan** [comment]
Hi @dalmo3, thanks for your feedback! It indeed is a bug. I will look at it asap.
