### ISSUE TITLE
Security vulnerabilities

### ISSUE THREAD

**Issue by xPh03niX** [onderceylan/pwa-asset-generator#280]
**Describe the bug**
Prototype pollution risk with two nested dependencies, 

* Update minimist to version 1.2.3 or newer
Path: pwa-asset-generator > chrome-launcher > mkdirp > minimist
* Update yargs-parser to version 18.1.2 or newer
Path: pwa-asset-generator > meow > yargs-parser

**To Reproduce**
1. Install the package using node
2. npm audit
3. See error

**Expected behavior**
No security alerts for that reason anymore

**System (please complete the following information):**
 * Any system.

**Additional context**
Just that, two packages need to be updated.

**Comment by onderceylan** [comment]
Hey @xPh03niX, thanks for the feedback. There's a new release in the process already and it will fix this issue as well.

**Comment by xPh03niX** [comment]
Thanks for the quick solution, you're cool.
