### ISSUE TITLE
Background is never transparent

### ISSUE THREAD

**Issue by ChelloApps** [onderceylan/pwa-asset-generator#296]
**Describe the bug**
Background is always solid white, I can't seem to make it transparent?

**To Reproduce**
pwa-asset-generator check-double-duotone.png --favicon --path-override ./assets/icons --type png

**Expected behavior**
Based upon the documentation the background should be transparent.

**System (please complete the following information):**
 - OS: Windows 10
 - node version: v10.15.2
 - npm version: 6.4.1
 - cli version: 3.0.0

**Additional context**
I have attached the image I have used as a source

![check-double-duotone](https://user-images.githubusercontent.com/52849690/83103080-e0d40880-a0ad-11ea-9d75-b51172777731.png)

**Comment by onderceylan** [comment]
Hi @ChelloApps, thanks for using pwa-asset-generator and sharing this feedback! 

Creating transparent images require `--opaque false` parameter. This is documented on the FAQ section of the README: https://github.com/onderceylan/pwa-asset-generator#how-can-i-generate-a-png-image-with-a-transparency

Once you provide that parameter along with `--type png`, you should have transparent images.
