### ISSUE TITLE
Prevent reformatting index.html

### ISSUE THREAD

**Issue by onderceylan** [onderceylan/pwa-asset-generator#30]
When index.html is provided as an output, cheerio reformats the code style on the file while adding the html tags. It also creates empty new lines when modification happens on already processed index.html file.

**Comment by sandeep206** [comment]
Hi Onder, I would like to pick this issue. I saw the code and I was thinking of removing the new line being added(append/prepend) while inserting to the HEAD tag. And was also thinking of using npm package `js-beautify` to reformat the html.  I can create a PR, if this is ok for you. Cheers, Sandeep

**Comment by onderceylan** [comment]
Hey Sandeep, thanks for the help! It's much appreciated. What I'd like to accomplish here is not minification of html output but avoid re-formatting the target html file altogether. 

Cheerio re-formats the html file so the format of the target html changes, like tabs/spaces/indentation added that users might not really enjoy. 

We need to update html file by adding the generated meta tags to the correct place and replace the old ones if they're there. And, do this without touching the rest of the html file.
