### ISSUE TITLE
Use sRGB color profile

### ISSUE THREAD

**Issue by kasperkamperman** [onderceylan/pwa-asset-generator#325]
**Describe the bug**
I'm using a specific purple color: #4f14bc as a background color and in my images (tested both svg and png). 
However this color comes out as: #3a1fb1 in PNG
And as #3c1eb0 in JPEG

**To Reproduce**
npx pwa-asset-generator Demo-Dot.svg ./bug/ --background "#4F14BC" --type png
npx pwa-asset-generator Demo-Dot.png ./bug/ --background "#4F14BC" --type png
npx pwa-asset-generator Demo-Dot.svg ./bug/ --background "#4F14BC" --type jpg
npx pwa-asset-generator Demo-Dot.png ./bug/ --background "#4F14BC" --type jpg

**Expected behavior**
icons and splash screens ending up with #4F14BC as color if I have used that as input. 

I couldn't attach svg directly so I zipped it. 

** original **
[Demo-Dot.svg.zip](https://github.com/onderceylan/pwa-asset-generator/files/4825055/Demo-Dot.svg.zip)
![Demo-Dot](https://user-images.githubusercontent.com/1760616/85547962-ba5aac00-b61e-11ea-8822-72655925d1c4.png)

** outcome **
![manifest-icon-512](https://user-images.githubusercontent.com/1760616/85548443-3b19a800-b61f-11ea-9609-1fe935bc456e.png)

![manifest-icon-512](https://user-images.githubusercontent.com/1760616/85548482-466cd380-b61f-11ea-9322-a4233a9d7d96.jpg)

**Comment by onderceylan** [comment]
Hi @kasperkamperman, thanks for your feedback! pwa-asset-generator doesn't do anything special for the rendering of the colors and the color codes in image output. It's all set by Puppeteer and Chromium based browser itself. 

Before digging in, may I ask you to try RGB color value instead, such as `--background "rgb(79,20,188)"` to see whether it meets your expectations? I also wonder if changing the image type to JPEG would make a difference.

**Comment by onderceylan** [comment]
I'm going to close this issue as by default a compression applies to the both image formats and color can change slightly.

**Comment by wojtekmaj** [comment]
I think I know where this issue could emerge from. Today I noticed that one of my splash screen renders in a slightly different color. After investigation it appears that one of the images (apple-splash-1125-2436) is being rendered with RGB as opposed to sRGB color profile.

**Comment by onderceylan** [comment]
Hey @wojtekmaj, thanks so much for shedding a light on this issue! There's a chrome flag forcing Chromium to run with sRGB color profile. I'm going to ship a new version with this fix.

**Comment by wojtekmaj** [comment]
Just tested it out and can confirm, it works like a charm!

**Comment by onderceylan** [comment]
Thanks for clarifying the issue, moreover testing and confirmation the fix @wojtekmaj! Really helpful.
