### ISSUE TITLE
xhtml: true has no effect

### ISSUE THREAD

**Issue by stevenmunro** [onderceylan/pwa-asset-generator#351]
Thanks for this promising icon generator.

`xhtml: true` appears to have no effect when used with the module (`const pwaAssetGenerator = require('pwa-asset-generator');`) example.

-x --xhtml                  Generate HTML meta tags by self-closing the tags  [default: false]

Is this the intended way to pass this flag?

**Comment by stevenmunro** [comment]
If I look at the `htmlMeta` object, I can see the self-closing tag being applied, however this is not making its way into the index.html file.

**Comment by onderceylan** [comment]
Hey @stevenmunro, thanks for using pwa-asset-generator and providing feedback for it! I've just verified the issue, I will look into it asap.
