### ISSUE TITLE
Incorrect file paths generated on Windows

### ISSUE THREAD

**Issue by leonelngande** [onderceylan/pwa-asset-generator#36]
**Describe the bug**
On Windows, the asset paths generated have double back-slashes (sometimes three) at the first directory level. This causes cli.test.js to fail, also user has to manually correct the asset paths generated.

**To Reproduce**
1. Execute cli command `git clone https://github.com/onderceylan/pwa-asset-generator.git`
2. `cd` to project root and execute cli command: `npm run jest`
3. See error

**Expected behavior**
cli.test.js should pass

**System (please complete the following information):**
 - OS: windows 10
 - node version: v10.15.3
 - npm version: 6.11.2
 - cli version: 1.1.6

**Screenshots**
![image](https://user-images.githubusercontent.com/13051253/64014435-ffef3b00-cb19-11e9-9868-0b38980e7c77.png)

**Comment by onderceylan** [comment]
Thanks for the issue @leonelngande! We need to fix the path issues on Windows asap.

**Comment by leonelngande** [comment]
Okay! Should I look into it? Have had a look at `helpers/file.js` and looks like that's where the paths are generated.

**Comment by onderceylan** [comment]
Please, I'd appreciate that as I have to spin off a VM to inspect. Feel free to work on it.

**Comment by leonelngande** [comment]
Great! On it thanks.
