### ISSUE TITLE
Running as CLI command on CI server causes Puppeteer error "zygote_host_impl_linux.cc(89) Running as root without --no-sandbox is not supported"

### ISSUE THREAD

**Issue by brandoncanaday** [onderceylan/pwa-asset-generator#364]
**Describe the bug**
Running this library as CLI command in a CI environment causes a Puppeteer error surrounding the Chrome launch option `--no-sandbox`. This library does not let you configure/add Chrome launch options, so this library is unusable whenever this issue arises.

**To Reproduce**
1. Execute cli command in CI environment (Gitlab, in this case): `npx pwa-asset-generator ./src/assets/logo.svg ./src/assets --icon-only --favicon --type png --opaque false -m ./src/manifest.json -i ./src/index.html`
2. Error below is produced:

```
> installer Chromium is not found in module folder, gonna have to download r756035 for you once 🤔
> installer Chromium downloaded to /builds/bcanaday96/angular-template/node_modules/puppeteer-core/.local-chromium/linux-756035
> cli Error: Failed to launch the browser process!
> ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
```

**Expected behavior**
There needs to be a CLI flag to add the `--no-sandbox` option.

**System (please complete the following information):**
 - OS: linux

**Comment by onderceylan** [comment]
Hi @brandoncanaday, thanks for reporting this issue. I've just release 3.2.0 version of PAG with latest puppeteer version. I've noticed similar reports in puppeteer repo and some of them are related to the dependencies of puppeteer. Can you please try again with the latest version of pwa-asset-generator and verify if issue still exists?

**Comment by brandoncanaday** [comment]
@onderceylan the same error unfortunately still exists with version 3.2.1. I still think adding an optional "--no-sandbox" option to the PAG CLI, as I proposed above, might fix it

**Comment by onderceylan** [comment]
Thanks for testing it @brandoncanaday, ok I will create a test release first to see whether the flag will make a difference in your use case. I will reply here with the test version on npm as soon as it's ready.

**Comment by onderceylan** [comment]
Hey @brandoncanaday, I have doubts about adding this option to the library as it may bring [serious security concerns](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#setting-up-chrome-linux-sandbox) when a local or remote HTML input is provided. I'm thinking of adding this option only if there an image input. Does your use case include HTML inputs?

**Comment by brandoncanaday** [comment]
My case is just an image. Judging from this line from your link

> If you absolutely trust the content you open in Chrome, you can launch Chrome with the --no-sandbox argument”


I think I agree with you about not allowing this option with any remote input.

**Comment by Rivers47** [comment]
I tried to run with --no-sandbox but the problem persists. It turned out that the order of options matter and you have to put it in front of other options
