### ISSUE TITLE
Some modifications from a fork

### ISSUE THREAD

**Issue by ranb2002** [onderceylan/pwa-asset-generator#389]
Hi Önder Ceylan,

Thank you for your generator, it was really useful for my latest projects. :)

I made **[some changes](https://github.com/ranb2002/pwa-asset-generator/pull/1)** to your code for my use case inside my fork. One of the modification was to generate MS Tiles icons (like https://github.com/onderceylan/pwa-asset-generator/issues/309)

**Would you want me to make a pull request against your repository for the changes you want?**

Or, feel free to copy and paste or even adapt my modifications. ;)

**Comment by onderceylan** [comment]
Hey @ranb2002, thank you for your feedback and for the improvement ideas you shared! Would you like to contribute with the MS Tiles icons change of yours for starters? That's a very good candidate imho as it's an active feature request as you referred.
