### ISSUE TITLE
Splash screens for iPhone 6/7/8 Plus have the wrong resultion

### ISSUE THREAD

**Issue by fabianeichinger** [onderceylan/pwa-asset-generator#391]
Probably related to the parsing chances in #362. iPhone 6 Plus is listed as 1920x1080, which is the physical resolution of the display, but the device uses and requires a splash screen with the logical resolution 414x736@3x.

**Comment by MrRobotjs** [comment]
same issue here.

**Comment by onderceylan** [comment]
Hi @fabianeichinger and @MrRobotjs, thanks for reporting this issue. I've just reproduced the issue myself. I will come up with a fix soon.
