### ISSUE TITLE
iOS icon & index.html revise

### ISSUE THREAD

**Issue by Wasenshi123** [onderceylan/pwa-asset-generator#433]
about generating iOS icon and changing index.html file, **regarding to `apple-touch-icon`**

According to this guideline that I have found:

![image](https://user-images.githubusercontent.com/12524716/97202958-dba6f100-17e6-11eb-85e8-ae1ae1597ba9.png)

**I propose to change the way this generator modify index.html to include only the default `<link rel="apple-touch-icon" href="...">` linked to 180x180 image.**

**Or add an option for this.**

Additional info: 
I have tested this on iOS 13.7, iPhone X, which should use 180x180 (@3x), but the result is, the icon is blurry.

Then I found out that this is because the iOS/Safari selectively uses a 120x120 (@2x) version instead of 180x180, and this is according to their rule.

But when I modify index.html to include only the default one linked to 180x180 like suggest above, the icon is clear, and the 180x180 (@3x) version is used correctly.

**Comment by Wasenshi123** [comment]
By the way, thank you for making this lovely helper. I really like it. :)

**Comment by onderceylan** [comment]
Hi @Wasenshi123, thanks for your feedback and opening this improvement item! Your proposition makes sense, I'm going to reduce it to only one version. Btw, feel free to open a PR about it and link it to this issue.
