### ISSUE TITLE
Release 1.3.0 breaks relative source file locations

### ISSUE THREAD

**Issue by dscheffy** [onderceylan/pwa-asset-generator#45]
**Describe the bug**
After upgrading to 1.3.0, "npx pwa-asset-generator logo.svg" stopped working. The output files all had the typical "missing image" that you've scene in browsers before. I haven't fully diagnosed the problem, but it still works with absolute urls and with absolute paths for local files, just not relative ones.

**To Reproduce**
1. create a new directory, copy some image to that directory
2. run `npx pwa-asset-generator <your image file>`
3. open manifest-icon-512.png

**Expected behavior**
manifest-icon-512.png should contain my image (but it doesn't)

**System (please complete the following information):**
 - OS: macOS high sierra
 - node version v11.10.0
 - npm version 6.10.3
 - cli version 1.3.0 (note, it works fine in 1.2.0)

**Screenshots**
![manifest-icon-512](https://user-images.githubusercontent.com/1462805/65689907-37e09400-e06e-11e9-9cd0-66994dedd8c9.png)

**Comment by onderceylan** [comment]
Hi @dscheffy, thanks a lot for raising this issue. I was able to reproduce the same issue, I will release a fix asap.

**Comment by onderceylan** [comment]
Just fixed the issue @dscheffy, I'll add more tests to cover issues like this in future, including visual diff on generated files. CD pipeline will publish 1.3.1 in minutes.
