### ISSUE TITLE
iPhone 12 Pro sizes

### ISSUE THREAD

**Issue by samselikoff** [onderceylan/pwa-asset-generator#454]
I don't think iPhone 12 Pro has a corresponding link generated. I believe the resolution is 2,532 x 1,170.

I was under the impression the scraping tool would have caught this but is there a static place in this repo that requires it?

Thanks for this amazing tool!

**Comment by onderceylan** [comment]
Hey @samselikoff! Thanks for opening the issue. Unfortunately, Apple did not update [their dev site](https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/adaptivity-and-layout/) in a timely manner  yet, which is the data source where scraping happens. 

Considering Apple's delay on updating it's own site, I now think it might be better to maintain this specs manually and ditch the scraping part.

**Comment by samselikoff** [comment]
Gotcha. In the meantime is there an escape hatch , a way to add individual devices?

**Comment by samselikoff** [comment]
Awesome - nice work man!! Thank you!

**Comment by onderceylan** [comment]
Thanks for contributing @samselikoff! 😊
