### ISSUE TITLE
Question: landscape

### ISSUE THREAD

**Issue by lucasvazq** [onderceylan/pwa-asset-generator#48]
Hi!
What about the next screenshot? :

![Screenshot_20191007-000043_Chrome](https://user-images.githubusercontent.com/38964964/66282416-afe06280-e895-11e9-8a18-18c6e3ad16c2.jpg)

Does the generator currently cover all cases or any is missing?

**Comment by onderceylan** [comment]
Hi @lucasvazq, I believe this is a misunderstanding. The comment should be a response to the original post to AppScope post here, feedback for their online generator: https://medium.com/appscope/adding-custom-ios-splash-screens-to-your-progressive-web-app-41a9b18bdca3 which doesn't support landscape. PWA asset generator supports landscape. You can test it on an iOS simulator yourself 😉

**Comment by lucasvazq** [comment]
Thanks! It help me a lot bc I dont have apple software
