### ISSUE TITLE
Running as JSX implementation cause error: ` nod found: ./node_modules/chrome-launcher/dist/chrome-launcher.js`

### ISSUE THREAD

**Issue by xstable** [onderceylan/pwa-asset-generator#493]
I've installed pwa-asset-generator globally (and for testing purposes at the project with `yarn add pwa-asset-generator --dev`.

Then I've generated an own Component `PwaMetaTags` with the example in the documentation: 

```JS
import { appleDeviceSpecsForLaunchImages } from 'pwa-asset-generator';

export default () =>
    <>
      {appleDeviceSpecsForLaunchImages.map((spec) => {
        return (
          <>
            <link
              key={`apple-splash-${spec.portrait.width}-${spec.portrait.height}`}
              rel="apple-touch-startup-image"
              href={`apple-splash-${spec.portrait.width}-${spec.portrait.height}.png`}
              media={`(device-width: ${spec.portrait.width /
              spec.scaleFactor}px) and (device-height: ${spec.portrait
                .height /
              spec.scaleFactor}px) and (-webkit-device-pixel-ratio: ${
                spec.scaleFactor
              }) and (orientation: portrait)`}
            />
            <link
              key={`apple-splash-${spec.portrait.width}-${spec.portrait.height}`}
              rel="apple-touch-startup-image"
              href={`apple-splash-${spec.portrait.width}-${spec.portrait.height}.png`}
              media={`(device-width: ${spec.portrait.height /
              spec.scaleFactor}px) and (device-height: ${spec.portrait
                .width /
              spec.scaleFactor}px) and (-webkit-device-pixel-ratio: ${
                spec.scaleFactor
              }) and (orientation: landscape)`}
            />
          </>
        );
      })}
    </>
```

In my nextJS BasicLayout.js-Component, I add this :
```JS
import PwaMetaTags from './PwaMetaTags';

...
retrrn (
<>
  <Head>
          <PwaMetaTags />
  </Head>
</>
)
```

If I try to build the project, I got: 

> [PWA] Compile server
error - ./node_modules/chrome-launcher/dist/chrome-launcher.js:18:0
Module not found: Can't resolve 'child_process'

**Comment by onderceylan** [comment]
Hi @xstable, thanks for opening this issue and providing your feedback. 

I've checked your use case and it seems you might be using PAG on the runtime. As the library interacts with the filesystem, it must be used on the build time, and within the related lifecycle functions.

Here's two next.js functions that you can use PAG with:
* [getStaticProps](https://nextjs.org/docs/basic-features/data-fetching#getstaticprops-static-generation)
* [getServerSideProps](https://nextjs.org/docs/basic-features/data-fetching#getserversideprops-server-side-rendering)

Please let me know if it doesn't work for you.
