### ISSUE TITLE
Running with --xhtml - File stay's empty

### ISSUE THREAD

**Issue by xstable** [onderceylan/pwa-asset-generator#494]
I have this command: 
```
pwa-asset-generator ./public/assets/images/logo.svg ./public/assets/appIcons/ --path-override /assets/appIcons -m ./public/manifest.json -i ./public/assets/appIcons/index.html
```

This generates an HTML-File with the tags.

If this File still exist (generated with above command) and I add --xhtml, it replace the Content with the XHTML-Variant (with / right before >).

BUT... if I empty the whole index.html and run with --xhtml, the index.html stay empty... even if there is no Error-Message in the CLI: 
```
11:19:39 saveImages Saved image apple-splash-1242-2208 🙌
11:19:39 cli Icons are saved to Web App Manifest file ./public/manifest.json 🙌
11:19:39 cli iOS meta tags are saved to index html file ./public/assets/appIcons/index.html 
```
If I leave only `<html></html>` in this file, it is replaced to `<html/> after running with --xhtml
if I have only following in index.html:  `<html><head></head><body></body></html>`, it also work like expected.

Seams that --xhtml must have an <html><head>-Structure, while without --xhtml the script don't need it at all.

Would be fine if the script could create the needed HTML-Structure like it's currently without --xhtml

**Comment by onderceylan** [comment]
Hi @xstable, thanks for providing your feedback. 

I will look into how to improve the CLI feedback in case there's this error. It's not PAG's responsibility to scaffold the structure for the users, and there will be always an expectation for HTML files having some sort of content and structure. 

I will close the ticket for now and wait for more responses about this use case before putting an effort.
