### ISSUE TITLE
Wrong FileTypes

### ISSUE THREAD

**Issue by xstable** [onderceylan/pwa-asset-generator#495]
If you generate a favicon with following command:
```bash
npx pwa-asset-generator ./public/assets/images/logo.svg ./public/assets/appIcons/ --path-override /assets/appIcons -m ./public/manifest.json -i ./public/assets/appIcons/index.html --favicon --padding "10px" 
```

it generates a wrong link-tag:
```
    <link
      rel="icon"
      type="image/png"
      sizes="196x196"
      href="/assets/appIcons/favicon-196.jpg"
    />
```

As you se, type === image/png, but the filename is `favicon-196.jpg`
The file which is really generated was also an png. So the link-tag-generation has an issue because it set a non existing filetype.

**Comment by onderceylan** [comment]
Hey @xstable, thanks for reporting the issue. I will look into it asap.

**Comment by atjn** [comment]
I'm having the same issue. All of my favicons and mstile icons are generated in `.png` but the html links are to a `.jpg` file. I solve this issue by specifying `type: png` when running the script. I will happily provide more info if needed, but I don't think it is hard to replicate.
