### ISSUE TITLE
Is it possible to pass args to puppeteer such as "--disable-dev-shm-usage" ?

### ISSUE THREAD

**Issue by CharlesGrimont** [onderceylan/pwa-asset-generator#517]
Hi !

Is it possible to pass args to puppeteer such as "--disable-dev-shm-usage" ?

Thanks

**Comment by onderceylan** [comment]
Hi @CharlesGrimont, thanks for your feedback. I think this arg can be one of the default args in the library. Let me do some tests on it.

**Comment by CharlesGrimont** [comment]
Hi !

Did you find any time to perform some tests ? 

Would you like some help ?

Regards

**Comment by onderceylan** [comment]
Hi @CharlesGrimont, this was added on version [4.2.0](https://github.com/onderceylan/pwa-asset-generator/releases/tag/v4.2.0) and reverted with version 4.2.1 because it created issues for users on linux.

Can you please test your use case with version 4.2.0 and share your findings here?
