### ISSUE TITLE
npm detects vulnerability

### ISSUE THREAD

**Issue by guidupuy** [onderceylan/pwa-asset-generator#53]
**Describe the bug**
When running `npm audit`, a high severity vulnerability is detected

**To Reproduce**
1. Execute cli command `npm audit`

**Expected behavior**
No vulnerability gets flagged

**System (please complete the following information):**
 - macOS Catalina
 - node version v10.16.0
 - npm version 6.9.0
 - cli version 1.1.6

**Screenshots**
![Screen Shot 2019-10-19 at 11 23 37 PM](https://user-images.githubusercontent.com/1026103/67151539-f5565400-f2c7-11e9-9e15-93b769bffb8f.png)

**Additional context**
None

**Comment by onderceylan** [comment]
Hi @guidupuy, thanks for the report. I just created an issue on puppeteer repo. I will upgrade the package as soon as there's an update over https://github.com/GoogleChrome/puppeteer/issues/5055

**Comment by onderceylan** [comment]
Looks like the change is done on puppeteer, awaiting the release. It can be watched over here: https://github.com/GoogleChrome/puppeteer/pull/5016. As soon as it's released, I'll bump puppeteer version and publish a new version for pwa-asset-generator.
