### ISSUE TITLE
Question : How to make image smaller relative to the background ?

### ISSUE THREAD

**Issue by x4080** [onderceylan/pwa-asset-generator#54]
If I use margin 30%, some of the generated splashscreen is empty

Thanks

**Comment by onderceylan** [comment]
Hi @x4080, the default value for the padding surrounding the image is 10%. But it's just a css padding value that you can configure and override yourself with **-p --padding** option.

The lib already provides an architecture to fix your problem. It requires some css optimisation though.

1. You can use a more advanced padding value based on your taste and goal;
**Larger logo:** `--padding "calc(50vh - 20%) calc(50vw - 40%)"`
**Smaller logo:** `--padding "calc(50vh - 5%) calc(50vw - 10%)"`

2. You can create your own html input file which uses css media queries and provides different padding options based on breakpoints: https://material.io/design/layout/responsive-layout-grid.html#breakpoints

Would one of those work out for you?

**Comment by x4080** [comment]
Thanks for quick reply, I will try it and let you now

**Comment by x4080** [comment]
It works, thanks a lot @onderceylan
