### ISSUE TITLE
Logo size in landscape format is tiny compared to portrait

### ISSUE THREAD

**Issue by fabyeah** [onderceylan/pwa-asset-generator#557]
It seems like whatever resizing is done in portrait mode, isn't (properly) applied in landscape mode? As the logo in the landscape assets is very small compared to portrait.

PS: This lib is awesome and saved me a ton of time! 👏💯

**Comment by onderceylan** [comment]
Hi @fabyeah, thanks for your feedback ✌️

The example I added in the readme might be a solution to your issue. Could you please try the following?

> How can I make an image smaller or larger relative to the background?
>
> The default value for the padding surrounding the image is 10%. But it's just a css padding value that you can configure and override yourself with -p --padding option.
>
> You can use a more advanced padding value based on your taste and goal;
>
> Larger logo: --padding "calc(50vh - 20%) calc(50vw - 40%)"
> 
> Smaller logo: --padding "calc(50vh - 5%) calc(50vw - 10%)"
>
> You can create your own html input file which uses css media queries and provides different padding options based on breakpoints: https://material.io/design/layout/responsive-layout-grid.html#breakpoints

**Comment by fabyeah** [comment]
My source file actually had some padding already, so that's where part of the problem originated. But with the `--padding` parameter I was able to get the desired sizes for portrait and landscape. Thanks! 👍
