### ISSUE TITLE
Is it possible to set background image as background?

### ISSUE THREAD

**Issue by JB1905** [onderceylan/pwa-asset-generator#578]
Hi,

Is it possible to set background image as background value - pass url to image.

**Comment by onderceylan** [comment]
Hi @JB1905, pwa-asset-generator directly maps `background` value provided, to the css `background` property. This means, you can do what you want by passing `url()` arg like how you do it with css. Example;

`pwa-asset-generator -b "url('https://onderceylan.github.io/pwa-asset-generator/static/logo.png') repeat"`

Alternatively, you can provide your own HTML with your own style as an input. That would make it more flexible to design exactly what you wish by using web tech. Please see the relevant section on the readme related to the HTML inputs.

**Comment by jp06** [comment]
Oh, I never thought of using it like that. Thanks!
