### ISSUE TITLE
Chrome launcher does not exit properly on connection error

### ISSUE THREAD

**Issue by onderceylan** [onderceylan/pwa-asset-generator#58]
In case of `connect ECONNREFUSED` error, chrome launcher instances doesn't get killed. This creates memory issues and introduces SPOF for the lib. 

A preferred solution for this is to treat system browser initialization differently and let launcher handle the process management on error.

**Comment by elmeerr** [comment]
I'm facing this issue on a windows 10 machine.

```
Error: connect ECONNREFUSED 127.0.0.1:57911 �
Error: connect ECONNREFUSED 127.0.0.1:57932
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14)
Error: connect ECONNREFUSED 127.0.0.1:57920
```

Is there a workaround for this?

**Comment by onderceylan** [comment]
> Hi...nice CLI man, congrats!!
> 
> I'm facing this issue on a windows 10 machine.
> 
> ```
> Error: connect ECONNREFUSED 127.0.0.1:57911 �
> Error: connect ECONNREFUSED 127.0.0.1:57932
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14)
> Error: connect ECONNREFUSED 127.0.0.1:57920
> ```
> 
> Is there a workaround for this?

Hi @elmeerr, thank you! I think this is a bug introduced with v2. Can you please try installing v1.3.1 - https://www.npmjs.com/package/pwa-asset-generator/v/1.3.1? 

I’m working on the fix atm. Sorry for inconvenience.
