### ISSUE TITLE
If destination folder does not exist, no images created, but return code 0

### ISSUE THREAD

**Issue by leandrolerena** [onderceylan/pwa-asset-generator#581]
Just a small thing, but a fix would be very useful in automated environments.

**Description and Reproduction**

pwa-asset-generator src/assets/icons/icon.svg src/assets/icons/gen --type png

**If src/assets/icons/gen exists:**

- Images are created
- Exit code 0 (no error)

**If src/assets/icons/gen does not exist:**

- Images are **not** created
- Exit code 0 (no error)

**Expected behavior**

Return an error, if an error occurs

**System (please complete the following information):**
 - OS:Linux
 - node version v12.18.4
 - npm version 6.14.6
 - cli version 4.1.1

**Comment by leandrolerena** [comment]
Seems to be a weird issue on my side, couldn't reproduce after restart...

**Comment by onderceylan** [comment]
No worries, thanks for your attention @leandrolerena!
