### ISSUE TITLE
Path prefix encoding in index.html

### ISSUE THREAD

**Issue by r1m** [onderceylan/pwa-asset-generator#60]
**Describe the bug**
Path prefix are html encoded.
I'm trying to use this for a VueJS app. Index.html file is a template that will be augmented during the build process.

Typically it contains some templating for environment variables

```html
  <link rel="icon" href="<%= BASE_URL %>favicon.ico">
```
This tool is encoding any path, can we disable this behavior ?

**To Reproduce**
1. Execute cli command `pwa-asset-generator -i ./public/index.html -a "<%= BASE_URL %>" ./public/img/assets/logo.svg ./public/assets`
2. Open 'index.html'
3. <> are encoded

```
<link rel="icon" href="&lt;%= BASE_URL %&gt;favicon.ico">
```
**Expected behavior**

**System (please complete the following information):**
 - cli version 2.0.0

**Comment by onderceylan** [comment]
Hi @r1m, thanks for the feedback. I will be releasing the fix quite soon.

**Comment by r1m** [comment]
Wow, that was quick ! Thanks for the fix 👏
