### ISSUE TITLE
Unexpected string in JSON at position 290

### ISSUE THREAD

**Issue by dhofverberg** [onderceylan/pwa-asset-generator#600]
**Describe the bug**
Gets the following output:
2:06:32 AM getSplashScreenMetaData Initialising puppeteer to load latest splash screen metadata 🤖
2:06:32 AM getAppleSplashScreenData Navigating to Apple Human Interface Guidelines website - https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/adaptivity-and-layout/
2:06:37 AM getAppleSplashScreenData Waiting for the data table to be loaded
2:06:37 AM getAppleSplashScreenData Retrieved splash screen data
2:06:37 AM getSplashScreenMetaData Loaded metadata for iOS platform 🙌
2:06:37 AM saveImages Initialising puppeteer to take screenshots 🤖
2:06:37 AM getShellHtml Generating shell html with provided image source
2:06:37 AM getShellHtml Providing shell html as page content
2:06:39 AM saveImages Saved image apple-splash-1170-2532 🙌
2:06:41 AM saveImages Saved image apple-splash-1242-2688 🙌
2:06:41 AM saveImages Saved image apple-splash-1284-2778 🙌
2:06:41 AM saveImages Saved image apple-splash-1792-828 🙌
2:06:41 AM saveImages Saved image apple-splash-1334-750 🙌
2:06:41 AM saveImages Saved image apple-splash-1668-2388 🙌
2:06:41 AM saveImages Saved image apple-splash-2778-1284 🙌
2:06:41 AM saveImages Saved image apple-splash-2532-1170 🙌
2:06:41 AM saveImages Saved image apple-splash-2388-1668 🙌
2:06:41 AM saveImages Saved image apple-splash-1536-2048 🙌
2:06:41 AM saveImages Saved image manifest-icon-512 🙌
2:06:41 AM saveImages Saved image apple-splash-640-1136 🙌
2:06:41 AM saveImages Saved image apple-splash-2732-2048 🙌
2:06:41 AM saveImages Saved image apple-splash-2160-1620 🙌
2:06:41 AM saveImages Saved image apple-splash-2436-1125 🙌
2:06:41 AM saveImages Saved image apple-splash-2224-1668 🙌
2:06:41 AM saveImages Saved image apple-splash-2048-2732 🙌
2:06:41 AM saveImages Saved image apple-splash-2048-1536 🙌
2:06:41 AM saveImages Saved image apple-splash-828-1792 🙌
2:06:41 AM saveImages Saved image apple-icon-180 🙌
2:06:42 AM saveImages Saved image apple-splash-1125-2436 🙌
2:06:42 AM saveImages Saved image apple-splash-1242-2208 🙌
2:06:42 AM saveImages Saved image apple-splash-1668-2224 🙌
2:06:42 AM saveImages Saved image apple-splash-1136-640 🙌
2:06:42 AM saveImages Saved image apple-splash-1620-2160 🙌
2:06:42 AM saveImages Saved image apple-splash-750-1334 🙌
2:06:42 AM saveImages Saved image apple-splash-2688-1242 🙌
2:06:42 AM saveImages Saved image manifest-icon-192 🙌
2:06:42 AM saveImages Saved image apple-splash-2208-1242 🙌
2:06:42 AM cli SyntaxError: Unexpected string in JSON at position 290 😭

**To Reproduce**
Using the following parameters:
pwa-asset-generator logo_512x512.png ./ley/ -m ./manifest.json -i index.html -n

**Expected behavior**

**System (please complete the following information):**
 - OS: Linux (Ubuntu)
 - node version v10.19.0
 - npm version 6.14.4
 - cli version 4.1.1

**Screenshots**

**Additional context**
Any idea what is going on, or how to resolve it? Have I done something wrong?

**Comment by dhofverberg** [comment]
Sorry, just noticed an error in the manifest file - my bad. :(

**Comment by onderceylan** [comment]
No worries, thanks for your attention @dhofverberg!
