### ISSUE TITLE
Generate more favicon sizes

### ISSUE THREAD

**Issue by memeries** [onderceylan/pwa-asset-generator#606]
**Is your feature request related to a problem? Please describe.**

I use this program to generate favicons, but I only find `favicon-196.png` in the output

**Describe the solution you'd like**

Generate smaller sizes like `favicon.ico`, 16x16, 32x32, and 64x64

**Describe alternatives you've considered**

Using external generators or resizing by hand

**Additional context**

None

**Comment by justingolden21** [comment]
I was thinking this as well. What would be the use case for those icons though? Wouldn't 192 and 512 check all of the boxes according to the readme of this project?

**Comment by atjn** [comment]
As far as I know, browsers will at least download the 196x196 version of a favicon, just in case they need to display the icon in a larger box somewhere. Since they always do that, there is no reason to then also bloat the network connection with 64x64 and 32x32 versions of the image.

**Comment by onderceylan** [comment]
Thanks for the feedback folks. As @atjn mentioned, this is exactly the reason why we use a single size for favicons. Platforms already force us to bloat the apps we have with enough tags and images. So, unless it's absolutely necessary, I'm in favor of brevity in this area.
