### ISSUE TITLE
add favicon only flags 

### ISSUE THREAD

**Issue by Truth1984** [onderceylan/pwa-asset-generator#70]
Here is the situation,
I want to generate a transparent `favicon`, and white background for `splash` and `icon`, but there is no such option.

when I set `{favicon: true}`, the program automatically generate `icon & splash` for me 

Thus here is my workaround, first I generate `favicon` with `{ opaque: false, iconOnly: true, favicon: true }` and then overwrite it with `{background:"#FFFFFF", favicon:false}` option.

I wonder if we can add `faviconOnly` flag.

**Comment by onderceylan** [comment]
Hi @Truth1984, thanks for the feedback! Looks like you found a nice workaround for this edge case. 

Currently, generating favicon is coupled with app icon generation, which kinda made sense back then. But now I consider changing --favicon flag to --favicon-only by also decoupling it from the rest of icon generation.

**Comment by onderceylan** [comment]
After a second thought, I think it's better to park this issue for now by updating the FAQ section of the readme. Adding an additional faviconOnly flag will not help with reducing the CLI calls in this scenario and it will add more complexity to the lib by putting a focus on favicon, which shouldn't be the goal of the lib IMHO. We might resurrect it if it gets more attention from the users in the future ✌️Thanks for the help @Truth1984!
