### ISSUE TITLE
Deprecated media feature “device-width”

### ISSUE THREAD

**Issue by pniaps** [onderceylan/pwa-asset-generator#71]
After updating the source and validating, multiple error are shown.

line 47: Bad value “(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)” for attribute “media” on element “link”: Deprecated media feature “device-width”. For guidance, see the Deprecated Media Features section in the current Media Queries specification.

And this is that line:

`<link rel="apple-touch-startup-image" href="http://127.0.0.1/compro/public/pwa/apple-splash-2048-2732.png" media="(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)">`

Thanks.

**Comment by onderceylan** [comment]
Hi @pniaps, thanks for the feedback. Unfortunately, this is a tradeoff you have to make if you want to provide splash screens for iOS platform. As described in blog post in motivation, iOS doesn't respect Web App Manifest specs and it introduces it's own non-standard way of dealing with splash screens.

It's either validity of your HTML or the splash screen features on iOS. If you care about HTML validity, you can still go for **--icons-only** feature and declare icons for **manifest.json** which will display icons and splash screens on Android.

**Comment by pniaps** [comment]
Thanks for your response.
I didn't found that information before.
Thanks again.
