### ISSUE TITLE
Wrong filenames for manifest.json

### ISSUE THREAD

**Issue by almeric** [onderceylan/pwa-asset-generator#723]
**Describe the bug**
The filenames for the icons in the generated manifest file are not generated & will result in a 404 not found. 

**To Reproduce**
When running as a module with the following config:

```javascript
const { savedImages, htmlMeta, manifestJsonContent } = await pwaAssetGenerator.generateImages(
    './src/images/favicon/favicon_src.svg',
    './public/assets/images/favicon/',
    {
      scrape: false,
      favicon: true,
      mstile: true,
      portraitOnly: true,
      background: '#ffffff',
      type: 'png',
      pathOverride: '/assets/images/favicon',
      manifest: './public/manifest.json',
      log: false,
    }
  );

```

The following icons/splash images are generated:

```
apple-icon-180.png
apple-splash-640-1136.png
apple-splash-750-1334.png
apple-splash-828-1792.png
apple-splash-1125-2436.png
apple-splash-1170-2532.png
apple-splash-1242-2208.png
apple-splash-1242-2688.png
apple-splash-1284-2778.png
apple-splash-1536-2048.png
apple-splash-1620-2160.png
apple-splash-1668-2224.png
apple-splash-1668-2388.png
apple-splash-2048-2732.png
favicon-196.png
manifest-icon-192.maskable.png
manifest-icon-512.maskable.png
mstile-icon-128.png
mstile-icon-270.png
mstile-icon-558.png
mstile-icon-558-270.png
```

...but the following manifest data is generated:

```
[
  {
    src: '/assets/images/favicon/manifest-icon-192.png',
    sizes: '192x192',
    type: 'image/png',
    purpose: 'maskable'
  },
  {
    src: '/assets/images/favicon/manifest-icon-512.png',
    sizes: '512x512',
    type: 'image/png',
    purpose: 'maskable'
  }
]
```

As you can see above, `manifest-icon-192.png` & `manifest-icon-512.png` don't exist. `manifest-icon-512.maskable.png` & `manifest-icon-512.maskable.png` do exist however.

**Expected behavior**
The correct filenames are used in the generated manifest file.

**System (please complete the following information):**
 - OS: macOS 11.6
 - node version: v16.11.1
 - npm version: 8.0.0
 - pwa-asset-generator version: 5.0.0

**Comment by onderceylan** [comment]
Hey @almeric, thanks for reporting the issue. I've reproduced the same. The issue seems to be related to the `pathOverride` option conflict. I'm working on a fix.
