### ISSUE TITLE
5.0.0: Issues on Chrome 95

### ISSUE THREAD

**Issue by frederikhors** [onderceylan/pwa-asset-generator#725]
**Describe the bug**
Updating today from 4 to 5 and using the below simple command gives a manifest that Chrome 95 doesn't like:

![image](https://user-images.githubusercontent.com/41120635/139284783-4ccfcda7-b1df-48fd-9980-89b9b01a2b83.png)

**To Reproduce**
1. `npx pwa-asset-generator ./src/icons/icon.svg ./static/icons/ --index ./src/index.html --manifest ./static/manifest.json --type png --icon-only --favicon --padding false`

Generates this manifest.json:

```json
{
  "name": "MyApp",
  "description": "MyApp",
  "short_name": "MyApp",
  "start_url": ".",
  "display": "standalone",
  "background_color": "#ffffff",
  "theme_color": "#333333",
  "icons": [
    {
      "src": "images/icons/manifest-icon-192.maskable.png",
      "sizes": "192x192",
      "type": "image/png",
      "purpose": "maskable"
    },
    {
      "src": "images/icons/manifest-icon-512.maskable.png",
      "sizes": "512x512",
      "type": "image/png",
      "purpose": "maskable"
    }
  ]
}
```

**Expected behavior**
I would like to have a default configuration to follow for no issues in Chrome.

**System (please complete the following information):**
 - OS: win 10
 - node version: 14
 - npm version: 8.1.1
 - cli version: 5.0.0

**Comment by onderceylan** [comment]
Thanks for reporting this issue. As of latest changes on Chrome and Lighthouse audits,

* `maskable any` value is not recommended anymore.
* There should be at least one icon with the `any` purpose, or without the purpose altogether
* There should be at least oen icon with the `maskable` purpose

I'm working on a change to reflect this requirements update.
