### ISSUE TITLE
[question]: (Potentially) missing icon sizes

### ISSUE THREAD

**Issue by ChristofferSkog21st** [onderceylan/pwa-asset-generator#74]
When you create a PWA app using Angular CLI the following sizes are added to your manifest file:

```
   {
      "src": "assets/icons/icon-72x72.png",
      "sizes": "72x72",
      "type": "image/png"
    },
    {
      "src": "assets/icons/icon-96x96.png",
      "sizes": "96x96",
      "type": "image/png"
    },
    {
      "src": "assets/icons/icon-128x128.png",
      "sizes": "128x128",
      "type": "image/png"
    },
    {
      "src": "assets/icons/icon-144x144.png",
      "sizes": "144x144",
      "type": "image/png"
    },
    {
      "src": "assets/icons/icon-152x152.png",
      "sizes": "152x152",
      "type": "image/png"
    },
    {
      "src": "assets/icons/icon-192x192.png",
      "sizes": "192x192",
      "type": "image/png"
    },
    {
      "src": "assets/icons/icon-384x384.png",
      "sizes": "384x384",
      "type": "image/png"
    },
    {
      "src": "assets/icons/icon-512x512.png",
      "sizes": "512x512",
      "type": "image/png"
    }
```

However, when you generate sizes using this package the only ones that are changed are the last three:

   ```
 {
      "src": "assets/icons/icon-384x384.png",
      "sizes": "384x384",
      "type": "image/png"
    },
    {
      "src": "assets/pwa/manifest-icon-192.png",
      "sizes": "192x192",
      "type": "image/png"
    },
    {
      "src": "assets/pwa/manifest-icon-512.png",
      "sizes": "512x512",
      "type": "image/png"
    }
```

Can you safely remove the other ones from the manifest file or should I create these images myself to be certain that it works as intended on every device?

You mention the following in the docs:

> Google’s Android platform respects Web App Manifest API specs and it expects you to provide at least 2 icon sizes in your manifest file

Is this the reason as to why there's only 3 sizes added?

**Comment by onderceylan** [comment]
Hi @ChristofferSkog21st, thanks for the question! pwa-asset-generator only generates 2 icons for the manifest, with the sizes of 192x192 and 512x512. This is documented both on the readme and the blog post linked on motivation. 

I also wonder why Angular CLI still generates all those sizes with their schematics, so maybe it's better to open an issue in their repo and ask them.

There's a discussion about this, including the idea to reduce the number of images required in manifest to only 512x512 one. You can read more about that discussion here: https://github.com/GoogleChrome/lighthouse/issues/291

For now, I prefer keeping the requirements stated on https://developers.google.com/web/fundamentals/web-app-manifest/#icons. Having said that, I recommend removing all other images and manifest.json entries on your angular project.

I don't think it's a good idea for pwa-asset-generator to take the ownership of manifest.json and do modifications on existing entries, so there's no plan to do that via PAG.
