### ISSUE TITLE
Error when icons key is missing from manifest json

### ISSUE THREAD

**Issue by tiborsaas** [onderceylan/pwa-asset-generator#75]
**Describe the bug**

I get the following error if the "icons" key is missing from the webapp manifest.

    3:22:41 AM cli TypeError: Cannot read property 'filter' of undefined 

**To Reproduce**

Remove icons key in manifest file and generate assets with: 

    pwa-asset-generator ./frontend/assets/logo.svg ./build -i ./index.html -m ./manifest.json -b #000000

**System (please complete the following information):**
 - OS: [windows 10]
 - node version [v12.13.1]
 - cli version [2.1.2]

**Comment by onderceylan** [comment]
Hi @tiborsaas, thanks for filing the issue. I will look into it.
