### ISSUE TITLE
cli Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by Mellis84** [onderceylan/pwa-asset-generator#76]
I seem to get a "cli Error: EISDIR: illegal operation on a directory, read" when trying to update the index.html and manifest file. I'm using NPX, I have tried deleting my npmrc and .yarnrc, but no luck :(

**Comment by onderceylan** [comment]
Hey @Mellis84, thanks for the issue. Can you please share the command you try to execute? It seems like you point a folder instead a path to the file.

**Comment by Mellis84** [comment]
Thanks for the quick reply dude.

npx pwa-asset-generator ./src/logo.png ./assets -i ./public/index.html -m ./public/manifest.json

**Comment by onderceylan** [comment]
No worries, happy to help :) Is there any errors if you don't provide index.html and manifest.json file flags?

**Comment by Mellis84** [comment]
No, no errors, only if I try to generate an updated index or manifest file

**Comment by onderceylan** [comment]
Then I suspect there might be a permission issue on ./public folder. Can you pls check who owns that folder and what access rights are set on it?

**Comment by Mellis84** [comment]
Ok so, for some reason, the permissions were set to (me) which was Read & write but I also decided to set everyone to Read & write and now it works :| strange huh!?

Sorry If I wasted your time dude, I thought if I was set to Read & Write it would be fine.

**Comment by onderceylan** [comment]
No worries, I'm happy to hear it's resolved now :) Have fun using PAG!
