### ISSUE TITLE
URGENT! Puppeteer (12) error from 6.0.3 after update from 11

### ISSUE THREAD

**Issue by frederikhors** [onderceylan/pwa-asset-generator#764]
**Describe the bug**
Issue running generation from 6.0.3.

I saw you updated `puppeteer-core` from 11.0.0 to 12.0.0. This is the problem.

**Comment by onderceylan** [comment]
Thanks for reporting this @frederikhors, the fix is on the way.

**Comment by frederikhors** [comment]
I think dependabot is not useful.
